language: r
cache: packages
os: linux
env: R_CODECOV=true

r_packages:
  - covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
